version: '3.8'

# Services
services:

    # PHP Service
    php:
        build:
            dockerfile: Dockerfile
            context: ./php/
        container_name: chat-app-php
        volumes:
            - './php:/var/www/html'
        depends_on:
            - mariadb

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: chat-app-nginx
        ports:
            - 8080:80
        links:
            - 'php'
        volumes:
            - './php:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
        depends_on:
            - php

    # MariaDB Service
    mariadb:
        image: mariadb:10.9
        container_name: chat-app-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysqldata:/var/lib/mysql

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: chat-app-phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb

# Volumes
volumes:

  mysqldata: